矩阵练习

In [1]:
# 只有一个元素组成的张量为标量
import torch

x = torch.tensor([2.0])
y = torch.tensor([4.0])

x  + y, x *  y,x / y, x**y



(tensor([6.]), tensor([8.]), tensor([0.5000]), tensor([16.]))

In [2]:
# 向量可以看作标量值组成的列表

z = torch.arange(5)
z

tensor([0, 1, 2, 3, 4])

In [8]:
# 1.索引访问、切片
print(z[3], z[1:4])

tensor(3) tensor([1, 2, 3])


In [9]:
# 2. 访问长度、形状和维度
print(len(z), z.shape, z.ndim)

# 注意：一维的张量，它的形状只有一个元素

5 torch.Size([5]) 1


In [12]:
# 3.自定义创建矩阵

A = torch.arange(20).reshape(5,4)
print(A,"\n",A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]) 
 tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [14]:
# 对称矩阵（symmetric matrix）A等于其转置：A=A⊤
# 创建一个对称矩阵来验证一下

B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B,"\n",B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]]) 
 tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


In [15]:
# 多维张量
X = torch.arange(24).reshape(2,3,4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [22]:
# 给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()#创建A的一个副本
print(A,"\n",A+B)

# 矩阵的哈达玛积（Hadamard product）是按对应位置元素乘积得到的矩阵，与原先矩阵同形状
print(A*B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [26]:
# 标量和矩阵的乘法
a = 2
C = torch.arange(24).reshape(2,3,4)
print(C)
print(a+C,"\n",a*C,"\n",(a*C).shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]]) 
 tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]]) 
 torch.Size([2, 3, 4])


张量求和

In [30]:
t = torch.arange(4, dtype=torch.float32)
t, t.sum()#张量的求和

(tensor([0., 1., 2., 3.]), tensor(6.))

In [32]:
print(A)
print(A.shape,A.sum())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4]) tensor(190.)


 指定张量沿哪一个轴来通过求和降低维度
 可以按照降维的思想理解：
 axis=0降的就是行的维度，因此按照列来求和；
 axis=1降的是列的维度，按照行来求和

In [35]:
# 1.按列求和
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape


(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [36]:
# 2.按行求和
A_sum_axis1 = A.sum(axis=1) 
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [37]:
A.sum(axis=0).sum(axis=0)  # 先按行求和，再对结果按行求和
# 等价于
# A.sum()  # 直接对所有元素求和

# A是一个5X4的张量，只有0维和1维，按照所有维度求和就是全部求和

tensor(190.)

In [38]:
# 一个与求和相关的量是平均值（mean或average）
print(A.mean())
print(A.sum()/A.numel())#numel返回张量中元素的数量,验证mean

tensor(9.5000)
tensor(9.5000)


In [39]:
# 可以按照行或者列求和
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [41]:
# 参数keepdims=True用于计算总和或均值时保持轴数不变
sum_A = A.sum(axis=1, keepdims=True)
A,sum_A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]))

In [42]:
# 通过广播将A除以sum_A，这样就会得到每个元素占该列总和的比例
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [44]:
# 某个轴计算A元素的累积总和
# 按照列计算A的累积总和
print(A.cumsum(axis=0))
# 按照行计算A的累积总和
print(A.cumsum(axis=1))

#cumulative sum  |  cumsum

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])
tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])


In [45]:
# 点积是相同位置的按元素乘积的总和
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [47]:
# 我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x * y)

# 注意区分两个矩阵的哈达玛积和点积，前者是按元素相乘得到一个矩阵，后者是按元素相乘后求和得到一个标量

tensor(6.)

In [50]:
# torch.mv(A, x) 就是专门用来计算矩阵向量积的函数
# 矩阵向量积Ax是一个长度为m的列向量，其第i个元素是点积a⊤ix
print(A, x)
print(A.shape, x.shape, torch.mv(A, x))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([0., 1., 2., 3.])
torch.Size([5, 4]) torch.Size([4]) tensor([ 14.,  38.,  62.,  86., 110.])


In [51]:
# 我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵

B = torch.ones(4, 3)
B,torch.mm(A, B)

# 其实没必要挖牛角尖，就是线代里学到的矩阵乘法，这里从矩阵的哈达玛积，到矩阵-向量积，再推广到矩阵-矩阵积
# 就是为了引出矩阵乘法罢了

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

只有区分，torch.mv(A, x)是矩阵向量积，torch.mm(A, B)是矩阵矩阵乘法

三种范数

PyTorch 的 torch.norm() 函数默认计算的是 Frobenius 范数，且该范数只和矩阵元素的平方和有关，与矩阵的形状无关

In [52]:
# L2范数是向量元素平方和的平方根：
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [53]:
# L1范数，它表示为向量元素的绝对值之和：
torch.abs(u).sum()

tensor(7.)

In [58]:
# 矩阵的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)

一点点奇怪的地方

In [56]:
torch.ones((4, 9))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
torch.ones(4, 9)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

torch.ones() 的官方定义是接收可变数量的整数参数，或者一个包含整数的序列（元组 / 列表） 来指定形状：
直接传多个整数：torch.ones(4, 9) → 把 4、9 分别识别为第一维、第二维的大小，对应形状 (4, 9)。
传一个元组：torch.ones((4, 9)) → 把元组 (4, 9) 解析成维度大小，结果也是形状 (4, 9)。