标量

In [4]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x**y

(tensor([5.]), tensor([6.]), tensor([9.]))

向量

In [5]:
x=torch.arange(4)
x
x[3]

tensor(3)

矩阵

In [6]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵A等于其转置

计算总和或均值时保持轴数不变

In [9]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

In [10]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

累计求和

In [11]:
A.cumsum(axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

范数

In [12]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

亚导数：一个点多个导数