存储梯度

In [8]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [9]:
x.requires_grad_(True)
x.grad

In [10]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [11]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [12]:
x.grad==4*x

tensor([True, True, True, True])

In [13]:
x.grad.zero_()#梯度清零
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [14]:
x.grad.zero_()#梯度清零
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

移动到计算图之外

In [15]:
x.grad.zero_()#梯度清零
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [16]:
x.grad.zero_()#梯度清零
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])