In [1]:
import torch

In [2]:
w = torch.tensor([3.0], requires_grad=True)
y = w**4 + 2*w**3
y.backward()
print(w.grad) 

tensor([162.])


In [3]:
x = torch.linspace(-2, 2, 5, requires_grad=True)
f = torch.sin(x**2)  
f.sum().backward()
print(x.grad)
x.grad.zero_() 
print(x.grad)  

tensor([ 2.6146, -1.0806,  0.0000,  1.0806, -2.6146])
tensor([0., 0., 0., 0., 0.])


In [5]:
# optimizer.zero_grad()
# for i, batch in enumerate(dataloader):
#     loss = model(batch)
#     loss.backward()
#     if (i+1) % 10 == 0:  
#         optimizer.step()
#         optimizer.zero_grad()

In [7]:
# total_norm = torch.sqrt(sum(p.grad.pow(2).sum() for p in model.parameters()))
# clip_coef = 1.0 / (total_norm + 1e-6)
# for p in model.parameters():
#     p.grad.mul_(clip_coef)

In [9]:
# a = torch.tensor(2.0, requires_grad=True)
# b = a**2
# c = b**2 
# c.backward(retain_graph=True)
# print(a.grad) 
# if hasattr(b, 'grad'): b.grad.zero_()

In [10]:
x = torch.tensor([5.0], requires_grad=True)
f = torch.relu(x-3)
f.backward(retain_graph=True)  
(-f).backward()                
print(x.grad) 

tensor([0.])


In [11]:
x = torch.tensor([4.0], requires_grad=True)
y = x**3
dy_dx = torch.autograd.grad(y, x)[0]
print(dy_dx)

tensor([48.])


In [12]:
w = torch.ones(3, requires_grad=True)
w.grad = torch.tensor([10., 20., 30.])
optimizer = torch.optim.SGD([w], lr=0.1)
optimizer.step()
print(w)

tensor([ 0., -1., -2.], requires_grad=True)


In [13]:
x = torch.tensor([2.0], requires_grad=True)
f = torch.log(1 + torch.exp(x))
grad = torch.autograd.grad(f, x, create_graph=True)[0]
grad2 = torch.autograd.grad(grad, x)[0]  # 二阶导
print(grad2)  # ≈0.10499 (σ(2)*(1-σ(2)))

tensor([0.1050])
